spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pinwo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl:
  # log-impl: org.apache.ibatis.logging.log4j.Log4jImpl   #不打印查询结果
  # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql、参数、查询结果


logging:
  level:
    com.yc.dao: debug
server:
  port: 8083